# Generated by Django 2.2.16 on 2023-03-04 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20230304_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Место для вашего комментария', verbose_name='Ваш комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Здесь будет отражена дата вашего комментария', verbose_name='Дата комментария')),
                ('author', models.ForeignKey(blank=True, help_text='Добавляет ссылку на автора комментария', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_users', to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на автора комментария')),
                ('post', models.ForeignKey(blank=True, help_text='Добавляет ссылку на пост, к которому будет оставлен комментарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_posts', to='posts.Post', verbose_name='Cсылка на пост')),
            ],
        ),
    ]
