# Generated by Django 2.2.16 on 2023-03-11 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20230309_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Место для вашего комментария', verbose_name='Ваш комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Здесь будет отражена дата вашего комментария', verbose_name='Дата комментария')),
                ('author', models.ForeignKey(help_text='Добавляет ссылку на автора комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на автора комментария')),
                ('post', models.ForeignKey(help_text='Добавляет ссылку на пост, к которому будетоставлен комментарий', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Cсылка на пост')),
            ],
        ),
    ]
