# Generated by Django 2.2.16 on 2023-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20230315_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Здесь будет отражена дата вашего комментария', verbose_name='Дата комментария'),
        ),
    ]
